const router = require('express').Router()

// const user_router = require('../modules/users/user.route')
const auth_router = require('../modules/auth/auth.routes')
const user_router = require('../modules/users/user.route')
const node_router = require('../modules/nodes/node.route')
const gateway_router = require('../modules/gateways/gateway.route')
const building_router = require('../modules/building/building.route')
const company_router = require('../modules/company/company.route')
const weather_router = require('../modules/weather/weather.routes')
const report_router = require('../modules/reports/report.route')
const alert_router = require('../modules/alertion/alert.route')
const fileRoutes = require('./file.routes')

router.use('/auth', auth_router)
router.use('/users', user_router)
router.use('/node', node_router)
router.use('/gateway', gateway_router)
router.use('/building', building_router)
router.use('/company', company_router)
router.use('/weather', weather_router)
router.use('/report', report_router)
router.use('/alert', alert_router)
router.use('/file', fileRoutes)
module.exports = router
