name: Deploy GSS Express Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t muhammadyusuf2766/gssiot-company-backend19.08.2025 -f DockerFile .
      - name: Publish Image to docker hub
        run: docker push muhammadyusuf2766/gssiot-company-backend19.08.2025:latest
      - name: Remove unused Docker images
        run: docker system prune -af

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull muhammadyusuf2766/gssiot-company-backend19.08.2025:latest
      - name: Delete old container
        run: docker rm -f muhammadyusuf2766/gssiot-company-backend19.08.2025
      - name: Run Docker Container
        run: |
          docker run -d -p 3000:3000 --name nodejs-app-container \
          -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
          -e JWT_SECRET_KEY='${{ secrets.JWT_SECRET_KEY }}' \
          -e TELEGRAM_BOT_TOKEN='${{secrets.TELEGRAM_BOT_TOKEN}}' \
          -e DEBUG_LOGER='${{secrets.DEBUG_LOGER}}' \
          muhammadyusuf2766/gssiot-company-backend19.08.2025
